carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, cart_checkout, cart_success_view

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^success/$', cart_success_view, name='success'),
	url(r'^checkout/$', cart_checkout, name='checkout'),
	url(r'^update/$', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView, GuestRegisterView, home_page #, guest_register_page
from django.views.generic import TemplateView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
from .views import contact_page
from billing.views import payment_method_view, payment_method_createview

from marketing.views import MarketingPreferenceUpdateView
urlpatterns = [

    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
	url(r'^product/', include('products.urls', namespace='product')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^logout/', LogoutView.as_view(), name='logout'),

    url(r'^order/', include('orders.urls', namespace='order')),
    
    url(r'^register/guest', GuestRegisterView.as_view(), name='guest'),
    
    url(r'^api/cart', cart_detail_api_view, name='api-cart'),
	url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^checkout/address/resuse/', checkout_address_reuse_view, name='reuse'),
    url(r'^checkout/address/create/', checkout_address_create_view, name='address'),
    url(r'^$', home_page, name='home'),
    url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^contact/', contact_page, name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^settings/email', MarketingPreferenceUpdateView.as_view(), name='marketing-pref')
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/main.css' %}">

<!-- Font Awesome CDN -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- jQuery Confirm CDN CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<!-- Stripe CSS -->
<link rel="stylesheet" href='{% static "css/stripe-custom-style.css" %}'>

templates/base/forms.html
{% extends "base.html" %}


{% block content %}

<div class='col-12 col-md-6 mx-auto'>
	<h1 class='my-3'>{{title}}</h1>
	<form method='POST' action='{% if action_url %}{{action_url}}{% endif %}'>{% csrf_token %}
		{% if next_url %}
		<input type="hidden" name='next' value='{{next_url}}'/>
		{% endif %}
		{{form.as_p}}
		<button type="submit" class= 'btn btn-default'>Save</button>
	</form>
</div>

{% endblock %}

templates/base/js.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> 

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<!-- jQuery Confirm CDN JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- Djano Ajax Security JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- eCommerce Custom JS -->
<script src='{% static "js/ecommerce.js" %}'></script>

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>

<!-- jsRender JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js"></script>
{% include "base/js_templates.html" %}


<!-- eCommerce Custom2 JS -->
<script src='{% static "js/ecommerce.main.js" %}'></script>

templates/base/js_templates.html
{% verbatim %}

<!-- Stripe js Template -->
<script id="stripeTemplate" type="text/x-jsrender">
	<form class='payment-form' action="" method="post" id="payment-form" 
	data-token='{{:publish_key}}' data-next-url='{{:next_url}}'>
			
	  <div class="form-row">
	   <!--  <label for="card-element">
	      Credit or debit card
	    </label> -->
	    <div id="card-element" class='form-control'>
	      <!-- A Stripe Element will be inserted here. -->
	    </div>

	    <!-- Used to display form errors. -->
	    <div id="card-errors" role="alert"></div>
	  </div>

	  <button class='btn btn-primary my-3 btn-load'>Add Payment Method</button>
	</form>
</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'product:list' as product_url %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}
{% url 'marketing-pref' as subscribe_url %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <div class='container-fluid'>
        <!-- Image and text -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
          <div class='container'>
              <a class="navbar-brand" href="#">
                <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
                Buy-Online
              </a>

              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">

                        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                          <a class="nav-link" href="{{home_url}}">Home<span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                          <a class="nav-link" href="{{contact_url}}">Contact</a>
                        </li>

                        <li class="nav-item {% if request.path == product_url %}active{% endif %}">
                          <a class="nav-link" href="{{product_url}}">Products</a>
                        </li>

                        

                        <!-- <li class="nav-item {% if request.path == subscribe_url %}active{% endif %}">
                          <a class="nav-link" href="{{subscribe_url}}">Subscribe</a>
                        </li> -->

                        {% if request.user.is_authenticated %}
                              <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
                                        <a class="dropdown-item" href="#">Billing</a>
                                        <a class="dropdown-item" href="#">Preferences</a>
                                        <a class="dropdown-item" href="#">History</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                                      </div>
                              </li>
                        {% else %}

                              <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                                  <a class="nav-link" href="{{register_url}}">Register</a>
                              </li>


                              <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                                  <a class="nav-link" href="{{login_url}}">Login</a>
                              </li>

                        {% endif %}

                        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                          <a class="nav-link" href="{{cart_url}}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                        </li>

                    </ul>

                    {% include "search/snippets/form-snippet.html" %}

                </div>
              </div>
        </nav>
    </div>

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>